### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by FishyMine** [MatrixTM/MHDDoS#331]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: [e.g. MacOS]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

A bug happened!

### Screenshots

https://imgur.com/PJioSa0

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/fishymine/Downloads/uwu/start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyRoxy/__init__.py", line 10, in <module>
    from socks import socksocket, SOCKS4, SOCKS5, HTTP
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/socks.py", line 61, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

**Comment by FishyMine** [comment]
Sorry, the device is actually MacOS.

**Comment by mikhailramlal** [comment]
i have this same issue pls help

**Comment by mikhailramlal** [comment]
nvm i found fix

**Comment by MHProDev** [comment]
@mikhailramlal share how fixed
