### ISSUE TITLE
[BUG Report]: No module named PyRoxy

### ISSUE THREAD

**Issue by ghgiStudios** [MatrixTM/MHDDoS#433]
### Version

2.4 (Default)

### Which section is the problem?

Other

### Please complete the following information

```true
OS: Tested windows (11) and linux (Mint & NixOS)
Python version: tested on 3.10.0 & python 2.7.9 & python 3.8.12

Issue is with the requirements.
```

### What happened (Describe the bug) ?

When attempting to install PyRoxy it just says 

Traceback (most recent call last):
  File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'

This happened on 3 different OS's and 3 different versions of python. Any idea whats going on?

(Yes i did install PyRoxy it still gives this error)

### Screenshots

https://snipboard.io/UHmZgB.jpg

### Please provide a link to a minimal reproduction of the bug

https://pastebin.com/CKxTM32p

### Relevant log output

```shell
Traceback (most recent call last):
  File "start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```

### Your code

```true
Forked the current version, Ran pip install PyRoxy gave error. (Tested on 3 different OS and 3 different versions on python)
```

**Comment by Gh0stD14l3r** [comment]
As a quick fix for this run Sudo -E python3 start.py ...........

if you run MHDDOS with just Sudo it will cause that error you must add the -E flag for it to work.

-E runs sudo environment for the user

**Comment by ghgiStudios** [comment]
> As a quick fix for this run Sudo -E python3 start.py ...........
> 
> if you run MHDDOS with just Sudo it will cause that error you must add the -E flag for it to work.
> 
> -E runs sudo environment for the user

I never ran MHDDoS as sudo, would that also cause the problem?

**Comment by Gh0stD14l3r** [comment]
Depends on your environment. I either use Kali, ubuntu or my RPi which has ubuntu. If i dont invoke sudo i get permission errors trying to create sockets, if i run it as sudo without -E environment set i get the issue from the OP.

**Comment by ghgiStudios** [comment]
> Depends on your environment. I either use Kali, ubuntu or my RPi which has ubuntu. If i dont invoke sudo i get permission errors trying to create sockets, if i run it as sudo without -E environment set i get the issue from the OP.

I was using replit which uses nix os

**Comment by etherealsunshine** [comment]
> As a quick fix for this run Sudo -E python3 start.py ...........
> 
> if you run MHDDOS with just Sudo it will cause that error you must add the -E flag for it to work.
> 
> -E runs sudo environment for the user

Hi it still doesn't work for me, any other fixes?
