### ISSUE TITLE
[BUG Report]: invalid literal for int() with base 10: 'txt'

### ISSUE THREAD

**Issue by fawniye** [MatrixTM/MHDDoS#491]
### Version

2.4 (Default)

### Which section is the problem?

L7 (DDoS Attack Layer 7)

### Please complete the following information

```true
- OS: CentOS (Google Cloud)
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version: 3.9.2
```

### What happened (Describe the bug) ?

Using `python3 start.py post http://88.198.14.11 1 10000 socks5. txt 100 100`, it returns with the error: 
```
/home/[].local/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/[]/MHDDoS/start.py", line 1586, in <module>
    rpc = int(argv[6])
ValueError: invalid literal for int() with base 10: 'txt'
```

I'm DDoSing the Live Layer 7 DSTAT Hetzner-1

### Screenshots

https://imgur.com/a/OiR5uw6

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/surxsc/MHDDoS/start.py", line 1586, in <module>
    rpc = int(argv[6])
ValueError: invalid literal for int() with base 10: 'txt'
```

### Additional context

To assist me to solve this issue.

**Comment by fawniye** [comment]
nvm i fixed it

**Comment by 2goese** [comment]
Mind telling how you fixed it?
