### ISSUE TITLE
PyRoxy

### ISSUE THREAD

**Issue by MirDay** [MatrixTM/MHDDoS#530]
Traceback (most recent call last):
  File "C:\Users\ц\MHDDoS\start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "C:\Users\ц\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyRoxy\__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "C:\Users\ц\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PyRoxy\GeoIP\__init__.py", line 7, in <module>
    _reader = _open(__dir__ / 'Sqlite/GeoLite2-Country.mmdb')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ц\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\maxminddb\__init__.py", line 80, in open_database
    return cast(Reader, _extension.Reader(database, mode))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: b'C:\\Users\\\xd1\x86\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\PyRoxy\\GeoIP\\Sqlite\\GeoLite2-Country.mmdb'

?

**Comment by MirDay** [comment]
![Uploading image_2024-01-10_023602708.png…]()

**Comment by MirDay** [comment]
![image_2024-01-10_023617460](https://github.com/MatrixTM/MHDDoS/assets/123764075/8c39ff74-1ce2-4030-a747-61d5199490c6)

**Comment by SquareDot3301** [comment]
I had the same issue. I install a conda env with the version of python "3.10.12" and it's work ! To do this : 

1. Go [here](https://www.anaconda.com/download/), download anaconda. Be sure to initialize your shell with conda !
2. Type :
```
conda create --name yourName python=3.10.12 numba inflect
conda activate yourName
cd MHDDOS
pip install -r ./requirements.txt
```
And now you're ready to start :)

**Comment by ANON89MOUS** [comment]
can you tell me the usage command ....i m failed to run it
