### ISSUE TITLE
error start.py

### ISSUE THREAD

**Issue by gituserclone** [MatrixTM/MHDDoS#559]
### Which section is this feature request for?

Wiki

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

im start file start.py is this error c:\Users\нелегал\Downloads\MHDDoS-main\MHDDoS-main\start.py:168: SyntaxWarning: invalid escape sequence '\d'
  IP = compile("(?:\d{1,3}\.){3}\d{1,3}")
c:\Users\нелегал\Downloads\MHDDoS-main\MHDDoS-main\start.py:169: SyntaxWarning: invalid escape sequence '\d'
  protocolRex = compile('"protocol":(\d+)')
Traceback (most recent call last):
  File "c:\Users\нелегал\Downloads\MHDDoS-main\MHDDoS-main\start.py", line 28, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "C:\Users\нелегал\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyRoxy\__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "C:\Users\нелегал\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyRoxy\GeoIP\__init__.py", line 7, in <module>
    _reader = _open(__dir__ / 'Sqlite/GeoLite2-Country.mmdb')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\нелегал\AppData\Local\Programs\Python\Python312\Lib\site-packages\maxminddb\__init__.py", line 80, in open_database
    return cast(Reader, _extension.Reader(database, mode))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: b'C:\\Users\\\xd0\xbd\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xb3\xd0\xb0\xd0\xbb\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\PyRoxy\\GeoIP\\Sqlite\\GeoLite2-Country.mmdb'

### Describe the solution you'd like

im dont know

### Additional context

![image](https://github.com/MatrixTM/MHDDoS/assets/171615103/c07c8cd2-5405-4d7e-bb0a-2505cc4f0028)

**Comment by mreduar** [comment]
@gituserclone Did you solve this problem?
